---
- name: Make sure the required related facts are available
  ansible.builtin.setup:
    gather_subset:
    - "!all"
    - "!min"
    - kernel
    - mounts

- name: Validate bigboot_size is not empty
  ansible.builtin.assert:
    that: bigboot_size | length >0
    fail_msg: "bigboot_size is empty"

- name: Capture boot device name
  ansible.builtin.set_fact:
    boot_device_name:
       "{{ ansible_facts.mounts | selectattr('mount', 'equalto', '/boot') | map(attribute='device') | first | regex_replace('[0-9]*', '') }}"

- name: Capture boot device current size
  ansible.builtin.set_fact:
    boot_device_size:
       "{{ ansible_facts.mounts | selectattr('mount', 'equalto', '/boot') | map(attribute='size_total') | first }}"

- name: Get kernel version
  ansible.builtin.set_fact:
    kernel_version: "{{ ansible_facts.kernel }}"

- name: Create a backup of the current initramfs
  ansible.builtin.copy:
    remote_src: true
    src: /boot/initramfs-{{ kernel_version }}.img
    dest: /boot/initramfs-{{ kernel_version }}.img.{{ bigboot_backup_extension }}
    mode: "0600"

- name: Copy extend boot dracut module
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/lib/dracut/modules.d/99extend_boot/
    mode: "0554"
  loop:
  - bigboot.sh
  - module-setup.sh
  - sfdisk.static

- name: Resolve and copy the shrink-start script
  ansible.builtin.template:
    src: increase-boot-partition.sh.j2
    dest: /usr/lib/dracut/modules.d/99extend_boot/increase-boot-partition.sh
    mode: '0554'

- name: Create a new initramfs with the extend boot module
  ansible.builtin.command: /usr/sbin/dracut -a extend_boot --kver {{ kernel_version }} --force
  changed_when: true

- name: Reboot the server
  ansible.builtin.reboot:
    post_reboot_delay: 30

- name: Restore previous initramfs
  ansible.builtin.copy:
    remote_src: true
    src: /boot/initramfs-{{ kernel_version }}.img.{{ bigboot_backup_extension }}
    dest: /boot/initramfs-{{ kernel_version }}.img
    mode: "0600"

- name: Remove initramfs backup file
  ansible.builtin.file:
    path: /boot/initramfs-{{ kernel_version }}.img.{{ bigboot_backup_extension }}
    state: absent

- name: Remove dracut extend boot module
  ansible.builtin.file:
    path: /usr/lib/dracut/modules.d/99extend_boot
    state: absent

- name: Retrieve mount points
  ansible.builtin.setup:
    gather_subset:
    - "!all"
    - "!min"
    - mounts

- name: Capture boot device new size
  ansible.builtin.set_fact:
    boot_device_new_size:
      "{{ ansible_facts.mounts | selectattr('mount', 'equalto', '/boot') | map(attribute='size_total') | first | int }}"

- name: Capture expected device size
  ansible.builtin.set_fact:
    expected_size: "{{ (bigboot_size | human_to_bytes| int) + (boot_device_size | int) }}"

- name: Validate boot partition new size
  ansible.builtin.assert:
    that:
    - expected_size == boot_device_new_size
    fail_msg: 'Boot partition expected size to be {{ expected_size| int | human_readable }} but found {{ boot_device_new_size| int | human_readable }}'
